name: boticario_app
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^4.0.4
  get: ^4.6.1
  crypto: ^3.0.1
  shared_preferences: ^2.0.13
  intl:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  mockito:
  flutter_launcher_icons: 
  flutter_native_splash: 

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_native_splash:
  image: assets/images/splash.png
  color: "ffffff"
  android_gravity: fill
  ios_content_mode: center
  android_disable_fullscreen: true
  android: true
  ios: true

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/icon.png"
  adaptive_icon_foreground: "assets/images/icon.png"